apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: static-website
        image: resh5/static_website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80