apiVersion: apps/v1
kind: Deployment
metadata:
  name: static_website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static_website
  template:
    metadata:
      labels:
        app: static_website
    spec:
      containers:
      - name: website
        image: resh5/static_website:latest
        ports:
        - containerPort: 80